Repository Team-Hankki/hankki-android, pull requests merged in 2024-08, with the labels that each got.

#145 [Fix/143] home UI & logic
  app/src/main/java/com/hankki/hankkijogbo/App.kt
  app/src/main/res/values/themes.xml
  data/home/src/main/java/com/hankki/data/home/repositoryImpl/HomeRepositoryImpl.kt
  data/report/src/main/java/com/hankki/data/report/datasourceimpl/ReportDataSourceImpl.kt
  domain/home/src/main/java/com/hankki/domain/home/entity/response/CategoriesEntity.kt
  domain/home/src/main/java/com/hankki/domain/home/entity/response/CategoryEntity.kt
  domain/home/src/main/java/com/hankki/domain/home/repository/HomeRepository.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/model/UniversityModel.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/main/src/main/java/com/hankki/feature/main/MainTab.kt
Labels: FIX 🛠️, 동민 👻

#147 [Fix/146] image compress error & Report Error
  core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
  core/common/src/main/java/com/hankki/core/common/utill/ContentUriRequestBody.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreViewModel.kt
Labels: FIX 🛠️, 동민 👻

#150 [Fix/#144] add padding to item
  feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
Labels: FIX 🛠️, UI 📱, 혜음 🥖

#149 [Fix/#148] add clear focus
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
Labels: FIX 🛠️, 동민 👻

#153 [Feature/#142] update README
  README.md
Labels: DOCS 📝, 동민 👻

#154 [Fix #152] Apply design padding
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
Labels: FIX 🛠️, 세영 🦌

#157 [Feature/#156] Show snack bar
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreDetailButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiSnackBar.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiTextSnackBarWithButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiWhiteSnackBarWIthButton.kt
  core/designsystem/src/main/res/values/string.xml
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeSideEffect.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/res/values/strings.xml
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishSideEffect.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  feature/report/src/main/res/values/strings.xml
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/navigation/navigateStoreDetail.kt
Labels: FEATURE ✨, 동민 👻

#160 [Fix/#159] Update login logo
  feature/login/src/main/res/drawable/login.xml
Labels: FIX 🛠️, 세영 🦌

#162 [Feature/#151] Move to store
  feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboSideEffect.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreViewModel.kt
Labels: FIX 🛠️, UI 📱, FEATURE ✨, 혜음 🥖

#158 [Feature/#155] Store detail UI
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreDetailButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/ImageDoubleButtonDialog.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailDialogState.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailSideEffect.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailState.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailMenuBox.kt
Labels: FIX 🛠️, FEATURE ✨, 세영 🦌

#166 [Feature #164] Add back pressed event
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
Labels: FIX 🛠️, FEATURE ✨, 혜음 🥖

#167 [Fix #161] kakao sdk
  data/home/build.gradle.kts
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginSideEffect.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginViewModel.kt
Labels: FIX 🛠️, 세영 🦌

#171 [Fix/#170] Edit modal
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MySideEffect.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
Labels: FIX 🛠️, UI 📱, 혜음 🥖

#165 [Fix/#163] Add navigate to home
  feature/my/src/main/java/com/hankki/feature/my/component/BaseEmptyView.kt
  feature/my/src/main/java/com/hankki/feature/my/component/MoveToHomeButton.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/res/values/strings.xml
Labels: FIX 🛠️, UI 📱, FEATURE ✨, 혜음 🥖

#173 [Fix #172] store detail modal discrpition
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
Labels: FIX 🛠️, 세영 🦌

#176 [Feature/#169] 1st qa
  core/common/src/main/java/com/hankki/core/common/utill/Regex.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/DoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTitleTextField.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeSideEffect.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishState.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/component/ReportFinishCard.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportSideEffect.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportState.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
  feature/report/src/main/res/values/strings.xml
Labels: FEATURE ✨, 동민 👻

#179 [Feature/#177] 2nd sprint UI change
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreDetailButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiCategoryChip.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiChipWithIcon.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/DoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/ImageDoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/layout/BaseEmptyView.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/layout/HankkiLoadingScreen.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/layout/LoadingScreen.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiWhiteSnackBarWIthButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTitleTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/topappbar/HankkiTopBar.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_home_selected.xml
  core/designsystem/src/main/res/drawable/ic_home_unselected.xml
  core/designsystem/src/main/res/drawable/ic_jaebo.xml
  core/designsystem/src/main/res/drawable/ic_map_here.xml
  core/designsystem/src/main/res/drawable/ic_my_selected.xml
  core/designsystem/src/main/res/drawable/ic_my_unselected.xml
  core/designsystem/src/main/res/drawable/img_empty.png
  core/designsystem/src/main/res/raw/loading.json
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/component/RepositionButton.kt
  feature/home/src/main/java/com/hankki/feature/home/model/ChipState.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/my/src/main/java/com/hankki/feature/my/component/AddJogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboShareButton.kt
  feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/res/drawable/img_empty.xml
  feature/report/src/main/java/com/hankki/feature/report/finish/component/ReportFinishCard.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/component/LocationItem.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/component/UniversityItem.kt
Labels: UI 📱, FEATURE ✨, 동민 👻

#175 [Fix/#168] Solve my jogbo
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
  feature/my/src/main/java/com/hankki/feature/my/component/AddJogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/model/MyJogboModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboViewModel.kt
  feature/my/src/main/res/values/strings.xml
Labels: FIX 🛠️, UI 📱, 혜음 🥖

#185 [Feature/#174] store detail
  core/common/src/main/java/com/hankki/core/common/extension/Format.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/topappbar/HankkiTopBar.kt
  core/designsystem/src/main/res/drawable/ic_add_circle_dark_plus.xml
  core/designsystem/src/main/res/drawable/ic_arrow_left_gray50.xml
  core/designsystem/src/main/res/drawable/img_store_default.xml
  data/storedetail/src/main/java/com/hankki/data/storedetail/datasource/StoreDetailDataSource.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/datasourceImpl/StoreDetailDataSourceImpl.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/repositoryImpl/StoreDetailRepositoryImpl.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/service/StoreDetailService.kt
  domain/storedetail/src/main/java/com/hankki/domain/storedetail/repository/StoreDetailRepository.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailItem.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailMenuBox.kt
  feature/storedetail/src/main/res/drawable/img_store_default.xml
Labels: FIX 🛠️, FEATURE ✨, 세영 🦌

#187 Feature #183: set nullable and default image
  core/designsystem/src/main/res/drawable/img_store_default.png
  data/home/src/main/java/com/hankki/data/home/dto/response/StoreThumbnailResponseDto.kt
  data/home/src/main/java/com/hankki/data/home/dto/response/StoresResponseDto.kt
  domain/home/src/main/java/com/hankki/domain/home/entity/response/StoreEntity.kt
  feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
  feature/home/src/main/java/com/hankki/feature/home/model/StoreItemModel.kt
Labels: FEATURE ✨, 동민 👻

#189 [Feature/#188] report branch process
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/layout/HankkiLoadingScreen.kt
  core/designsystem/src/main/res/raw/loading.json
  data/report/src/main/java/com/hankki/data/report/datasource/ReportDataSource.kt
  data/report/src/main/java/com/hankki/data/report/datasourceimpl/ReportDataSourceImpl.kt
  data/report/src/main/java/com/hankki/data/report/dto/request/ReportOtherSchoolStoreRequestDto.kt
  data/report/src/main/java/com/hankki/data/report/dto/response/StoreValidateResponseDto.kt
  data/report/src/main/java/com/hankki/data/report/repositoryimpl/ReportRepositoryImpl.kt
  data/report/src/main/java/com/hankki/data/report/service/ReportService.kt
  domain/report/src/main/java/com/hankki/domain/report/entity/response/StoreValidateResponseEntity.kt
  domain/report/src/main/java/com/hankki/domain/report/repository/ReportRepository.kt
  feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreSideEffect.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreState.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreViewModel.kt
Labels: FEATURE ✨, 동민 👻

#190 [Fix/#181] First my module qa
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/topappbar/HankkiTopBar.kt
  feature/my/src/main/java/com/hankki/feature/my/component/AddJogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithArrowIcon.kt
  feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithImageAndBorder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboItemText.kt
  feature/my/src/main/java/com/hankki/feature/my/component/MoveToHomeButton.kt
  feature/my/src/main/java/com/hankki/feature/my/component/NewJogboButton.kt
  feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailSideEffect.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboSideEffect.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
Labels: FIX 🛠️, UI 📱, FEATURE ✨, 혜음 🥖

#192 [Fix/#191] font change
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/bottomsheet/HankkiStoreJogboBottomSheet.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/AddPhotoButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/DialogWithDescription.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/DoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/ImageDoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/SingleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/layout/BaseEmptyView.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiTextSnackBar.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiTextSnackBarWithButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTitleTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Type.kt
  core/designsystem/src/main/res/drawable/img_store_default.png
  feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
  feature/login/src/main/java/com/hankki/feature/login/OnboardingRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithArrowIcon.kt
  feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithImageAndBorder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboShareButton.kt
  feature/my/src/main/java/com/hankki/feature/my/component/MoveToHomeButton.kt
  feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/component/ReportFinishCard.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/component/SelectedImageController.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/component/EmptyLocationView.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/component/LocationItem.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
Labels: FIX 🛠️, 동민 👻

#196 [Fix/#195] 1차 디자인 QA 구현
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/bottomsheet/HankkiStoreJogboBottomSheet.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/AddPhotoButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiChipWithIcon.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/ImageDoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiWhiteSnackBarWIthButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiSearchTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTitleTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/constant/Border.kt
  core/designsystem/src/main/res/drawable/ic_arrow_down_thick.xml
  core/designsystem/src/main/res/drawable/ic_dropdown_btn.xml
  core/designsystem/src/main/res/drawable/ic_like_heart.xml
  core/designsystem/src/main/res/values/string.xml
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/component/RepositionButton.kt
  feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/component/ReportFinishCard.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/model/LocationModel.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreSideEffect.kt
  feature/report/src/main/res/values/strings.xml
Labels: UI 📱, FEATURE ✨, 동민 👻

#202 [Feature/#201] store detail qa
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreDetailButton.kt
  core/designsystem/src/main/res/drawable/ic_arrow_left_gray50.xml
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/HankkiStoreDetailCategoryChip.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailMenuBox.kt
Labels: FIX 🛠️, UI 📱, 세영 🦌

#203 [Feature/#194] onboarding qa
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginViewModel.kt
  feature/login/src/main/java/com/hankki/feature/login/OnboardingRoute.kt
  feature/login/src/main/res/raw/step3.json
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
Labels: FIX 🛠️, UI 📱, 세영 🦌

#198 [Fix/#193] First my module QA
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
  core/designsystem/src/main/res/drawable/ic_add.xml
  core/designsystem/src/main/res/drawable/ic_arrow_right.xml
  core/designsystem/src/main/res/drawable/ic_good.xml
  core/designsystem/src/main/res/drawable/ic_my_store.xml
  core/designsystem/src/main/res/drawable/ic_share.xml
  data/my/src/main/java/com/hankki/data/my/dto/response/JogboDetailDto.kt
  data/my/src/main/java/com/hankki/data/my/dto/response/StoreDto.kt
  data/my/src/main/java/com/hankki/data/my/dto/response/UserInformationDto.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/MyJogboDetailEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/StoreEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/UserInformationEntity.kt
  feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithArrowIcon.kt
  feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithImageAndBorder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboShareButton.kt
  feature/my/src/main/java/com/hankki/feature/my/component/MoveToHomeButton.kt
  feature/my/src/main/java/com/hankki/feature/my/component/NewJogboButton.kt
  feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/model/MyJogboModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/model/MyModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/model/MyStoreModel.kt
  feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
  feature/my/src/main/res/drawable/ic_food_small.xml
  feature/my/src/main/res/drawable/ic_spoon.xml
  feature/my/src/main/res/drawable/img_list_0.xml
  feature/my/src/main/res/drawable/img_list_1.xml
  feature/my/src/main/res/drawable/img_list_2.xml
  feature/my/src/main/res/drawable/img_list_3.xml
  feature/my/src/main/res/drawable/img_my_profile.xml
  feature/my/src/main/res/drawable/img_user_image.xml
  feature/my/src/main/res/values/strings.xml
Labels: FIX 🛠️, UI 📱, FEATURE ✨, 혜음 🥖

#184 [Fix/#178] Add condition to store launched effect
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreViewModel.kt
Labels: FIX 🛠️, UI 📱, FEATURE ✨, 혜음 🥖

#204 [Feature/#186] login message
  core/designsystem/src/main/res/drawable/toast_background.xml
  core/network/src/main/java/com/hankki/core/network/OauthInterceptor.kt
  core/network/src/main/res/values/strings.xml
  data/token/build.gradle.kts
  data/token/src/androidTest/java/com/hankki/data/token/ExampleInstrumentedTest.kt
  feature/login/build.gradle.kts
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hankki/feature/main/splash/SplashViewModel.kt
  gradle/libs.versions.toml
Labels: FIX 🛠️, UI 📱, FEATURE ✨, 세영 🦌

#209 [Feature/#206] Update tos
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/my/src/main/res/values/strings.xml
Labels: FIX 🛠️, UI 📱, 혜음 🥖

#200 [Feature/#199] Update University Selection
  core/designsystem/src/main/res/drawable/img_white_gradient_top_middle.xml
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/component/UniversityItem.kt
Labels: FIX 🛠️, UI 📱, FEATURE ✨, 세영 🦌

#208 [Fix/#205] Update designsystem
  core/designsystem/src/main/res/drawable/ic_arrow_down.xml
  core/designsystem/src/main/res/drawable/ic_heart.xml
  core/designsystem/src/main/res/drawable/ic_report.xml
  core/designsystem/src/main/res/drawable/ic_search.xml
  core/designsystem/src/main/res/drawable/ic_x.xml
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/res/drawable/ic_like.xml
Labels: FIX 🛠️, UI 📱, 혜음 🥖

#210 [Feature/#207] Jogbo duplication
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
  feature/my/build.gradle.kts
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboSideEffect.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboViewModel.kt
  feature/my/src/main/res/values/strings.xml
Labels: FIX 🛠️, UI 📱, FEATURE ✨, 혜음 🥖

#212 [Feature/#211] add loading view
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/layout/HankkiLoadingScreen.kt
  core/designsystem/src/main/res/values/string.xml
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreState.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreViewModel.kt
Labels: FEATURE ✨, 동민 👻

#214 [Fix/#213] Second my module QA
  data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
  data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  data/my/src/main/java/com/hankki/data/my/service/MyService.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/component/AddJogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/component/JogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/component/JogboItemText.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/JogboHashtagChip.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/JogboShareButton.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/MoveToHomeButton.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyState.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/component/ArrowIconButton.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/component/ImageAndBorderButton.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboViewModel.kt
  feature/my/src/main/res/drawable/img_folder.xml
  feature/my/src/main/res/drawable/img_user_hand.xml
  feature/my/src/main/res/drawable/img_user_profile.xml
  feature/my/src/main/res/values/strings.xml
Labels: FIX 🛠️, UI 📱, 혜음 🥖

#216 [Feature #215] fix 2nd QA
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiCategoryChip.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiSnackBar.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/snackbar/HankkiWhiteSnackBarWIthButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/topappbar/HankkiTopBar.kt
  data/report/src/main/java/com/hankki/data/report/dto/request/ValidateStoreRequestDto.kt
  data/report/src/main/java/com/hankki/data/report/dto/response/StoreDetailNicknameResponseDto.kt
  data/universityselection/src/main/java/com/hankki/data/universityselection/dto/request/UniversitySelectionRequestDto.kt
  domain/report/src/main/java/com/hankki/domain/report/entity/request/ValidateStoreRequestEntity.kt
  domain/report/src/main/java/com/hankki/domain/report/entity/response/UserInfoResponseEntity.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreViewModel.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
Labels: FIX 🛠️, 동민 👻

#222 [Feature/#217] 2nd qa
  core/designsystem/src/main/res/values/string.xml
  data/storedetail/src/main/java/com/hankki/data/storedetail/datasource/StoreDetailDataSource.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/response/StoreDetailNicknameResponseDto.kt
  domain/storedetail/src/main/java/com/hankki/domain/storedetail/entity/StoreDetailNicknameEntity.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/res/drawable/img_gradient_frame.xml
Labels: FIX 🛠️, UI 📱, 세영 🦌

#219 [Fix/#218] 2nd my qa
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/SingleButtonDialog.kt
  core/designsystem/src/main/res/drawable/ic_my_store.xml
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/MoveToHomeButton.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
Labels: FIX 🛠️, UI 📱, 혜음 🥖

#221 [Fix/#220] 2nd qa
  data/home/src/main/java/com/hankki/data/home/dto/response/UniversityResponseDto.kt
  domain/home/src/main/java/com/hankki/domain/home/entity/response/UniversityResponseEntity.kt
  domain/universityselection/src/main/java/com/hankki/domain/universityselection/entity/UniversitySelectionEntity.kt
  domain/universityselection/src/main/java/com/hankki/domain/universityselection/entity/UniversitySelectionRequest.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionViewModel.kt
Labels: FIX 🛠️, 동민 👻

#228 [Feature/#226] add new jogbo after bottomsheet
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportState.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
Labels: UI 📱, FEATURE ✨, 동민 👻

#229 [Feature/#225]qa
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyState.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionState.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionViewModel.kt
Labels: FIX 🛠️, UI 📱, FEATURE ✨, 세영 🦌

#224 [Fix/#223] 2nd my qa
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/MoveToHomeButton.kt
  feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboViewModel.kt
  feature/my/src/main/res/values/strings.xml
  feature/storedetail/build.gradle.kts
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailSideEffect.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/navigation/navigateStoreDetail.kt
Labels: FIX 🛠️, UI 📱, 혜음 🥖

#231 [Feature/#230] amplitude
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hankki/hankkijogbo/App.kt
  core/common/build.gradle.kts
  core/common/src/main/java/com/hankki/core/common/amplitude/AmplitudeManager.kt
  core/common/src/main/java/com/hankki/core/common/amplitude/EventType.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
  feature/main/src/main/java/com/hankki/feature/main/MainActivity.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/main/src/main/java/com/hankki/feature/main/MainTab.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionSideEffect.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionViewModel.kt
  gradle/libs.versions.toml
Labels: FIX 🛠️, FEATURE ✨, 동민 👻

#234 [Feature#232] rollback
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
Labels: FEATURE ✨, 동민 👻

#237 [Fix #236] Delete !
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
Labels: FIX 🛠️, UI 📱, 세영 🦌

#235 [Fix #233] Third my QA
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
Labels: FIX 🛠️, UI 📱, 혜음 🥖

#239 [Fix #238] Align store item row to center
  feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
Labels: FIX 🛠️, UI 📱, 혜음 🥖
