Repository Team-Hankki/hankki-android, pull requests merged in 2024-07, with the labels that each got.

#11 [Feature/#8] font setting
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Type.kt
  core/designsystem/src/main/res/font/pretendard_bold.otf
  core/designsystem/src/main/res/font/pretendard_medium.otf
  core/designsystem/src/main/res/font/pretendard_regular.otf
  core/designsystem/src/main/res/font/pretendard_semibold.otf
  core/designsystem/src/main/res/font/suite_bold.ttf
  core/designsystem/src/main/res/font/suite_medium.ttf
  core/designsystem/src/main/res/font/suite_regular.ttf
  core/designsystem/src/main/res/font/suite_semibold.ttf
  core/designsystem/src/main/res/mipmap-anydpi/ic_launcher.xml
  core/designsystem/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  core/designsystem/src/main/res/mipmap-hdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/values/strings.xml
  core/designsystem/src/main/res/values/themes.xml
Labels: FEATURE ✨, 혜음 🥖

#12 [Feature/#6] naver map
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  build-logic/src/main/java/com/hankki/build_logic/KotlinAndroid.kt
  build-logic/src/main/java/hankki.kotlin.library.gradle.kts
  build.gradle.kts
  feature/home/build.gradle.kts
  feature/home/src/main/AndroidManifest.xml
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/com/hankki/feature/main/MainActivity.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
  feature/report/src/main/java/com/hankki/feature/report/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEATURE ✨, 동민 👻

#15 [Feature/#13] restructuring
  app/build.gradle.kts
  build-logic/src/main/java/hankki.android.data.gradle.kts
  build-logic/src/main/java/hankki.android.feature.gradle.kts
  core/network/build.gradle.kts
  core/network/src/main/java/com/hankki/core/network/NetworkModule.kt
  core/network/src/main/java/com/hankki/core/network/StringExt.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
Labels: FIX 🛠️, 동민 👻

#19 [Feature/#9] kakao login
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hankki/hankkijogbo/App.kt
  feature/login/.gitignore
  feature/login/build.gradle.kts
  feature/login/proguard-rules.pro
  feature/login/src/androidTest/java/com/hankki/feature/login/ExampleInstrumentedTest.kt
  feature/login/src/main/AndroidManifest.xml
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginSideEffect.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginState.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginViewModel.kt
  feature/login/src/main/java/com/hankki/feature/login/navigation/LoginNavigation.kt
  feature/login/src/test/java/com/hankki/feature/login/ExampleUnitTest.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEATURE ✨, 세영 🦌

#22 [Feature/#21] correction design system
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Color.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Type.kt
Labels: ADD ✚, 혜음 🥖

#24 [Feature/#18] my page view
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Type.kt
  domain/my/.gitignore
  domain/my/build.gradle.kts
  domain/my/src/main/java/com/hankki/domain/my/entity/UserInfoEntity.kt
  feature/my/build.gradle.kts
  feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/MyState.kt
  feature/my/src/main/java/com/hankki/feature/my/MyViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithArrowIcon.kt
  feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithImageAndBorder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/Title.kt
  feature/my/src/main/res/drawable/ic_arrow_right.xml
  feature/my/src/main/res/drawable/ic_good.xml
  feature/my/src/main/res/drawable/ic_mygraphic.xml
  feature/my/src/main/res/drawable/ic_report.xml
  feature/my/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: UI 📱, 혜음 🥖

#23 [Feature/#20] university selection
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/HankkiButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Color.kt
  domain/universityselection/.gitignore
  domain/universityselection/build.gradle.kts
  domain/universityselection/src/main/java/com/hankki/domain/universityselection/UniversitySelectionModel.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/report/src/main/java/com/hankki/feature/report/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  feature/universityselection/.gitignore
  feature/universityselection/build.gradle.kts
  feature/universityselection/proguard-rules.pro
  feature/universityselection/src/androidTest/java/com/hankki/feature/university/ExampleInstrumentedTest.kt
  feature/universityselection/src/main/AndroidManifest.xml
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionState.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionViewModel.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/component/UniversityItem.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/navigation/UniversitySelectionNavigation.kt
  feature/universityselection/src/main/res/values/strings.xml
  feature/universityselection/src/test/java/com/hankki/feature/university/ExampleUnitTest.kt
  settings.gradle.kts
Labels: UI 📱, 세영 🦌

#25 [Feature/#16] home Screen
  app/build.gradle.kts
  app/src/main/java/com/hankki/hankkijogbo/App.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/Card.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/bottomsheet/HankkiStoreJogboBottomSheet.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiCategoryChip.kt
  core/designsystem/src/main/res/drawable/ic_add_square_btn.xml
  core/designsystem/src/main/res/drawable/ic_arrow_down.xml
  core/designsystem/src/main/res/drawable/ic_arrow_up.xml
  core/designsystem/src/main/res/drawable/ic_check_btn.xml
  core/designsystem/src/main/res/drawable/ic_dropdown_btn.xml
  core/designsystem/src/main/res/drawable/ic_ellipse.xml
  core/designsystem/src/main/res/drawable/ic_food.xml
  core/designsystem/src/main/res/drawable/ic_heart.xml
  core/designsystem/src/main/res/drawable/ic_map_here.xml
  core/designsystem/src/main/res/drawable/ic_plus_btn_empty.xml
  core/designsystem/src/main/res/drawable/ic_plus_btn_filled.xml
  core/designsystem/src/main/res/drawable/ic_x.xml
  core/designsystem/src/main/res/values/string.xml
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeSideEffect.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiStateChip.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiTopBar.kt
  feature/home/src/main/java/com/hankki/feature/home/component/RepositionButton.kt
  feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
  feature/home/src/main/java/com/hankki/feature/home/model/ChipState.kt
  feature/home/src/main/java/com/hankki/feature/home/model/MarkerItem.kt
  feature/home/src/main/java/com/hankki/feature/home/model/PriceChipItem.kt
  feature/home/src/main/java/com/hankki/feature/home/model/StoreItemEntity.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/res/drawable/ic_launcher_background.xml
  feature/home/src/main/res/drawable/ic_launcher_foreground.xml
  feature/main/src/main/java/com/hankki/feature/main/MainActivity.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  gradle/libs.versions.toml
Labels: FEATURE ✨, 동민 👻

#28 [Feature/#27] bounce click
  core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
Labels: FEATURE ✨, 동민 👻

#31 [Feature#30] add font
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Type.kt
Labels: FEATURE ✨, 동민 👻

#32 [Feature/#29] components and more action
  core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/bottomsheet/HankkiStoreJogboBottomSheet.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/AddPhotoButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiChipWithIcon.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTitleTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_add_photo_alternate.xml
  core/designsystem/src/main/res/drawable/ic_search.xml
  core/designsystem/src/main/res/drawable/white_gradient.xml
  core/designsystem/src/main/res/values/string.xml
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiStateChip.kt
  feature/home/src/main/java/com/hankki/feature/home/model/MarkerItem.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/component/UniversityItem.kt
Labels: FEATURE ✨, 동민 👻

#35 [Feature/#17] kakao login token
  app/build.gradle.kts
  build-logic/src/main/java/hankki.android.data.gradle.kts
  core/common/build.gradle.kts
  core/common/src/main/java/com/hankki/core/common/utill/BaseResponse.kt
  core/datastore/build.gradle.kts
  core/datastore/src/main/java/com/hankki/core/datastore/MyClass.kt
  core/datastore/src/main/java/com/hankki/core/datastore/TokenDataStore.kt
  core/datastore/src/main/java/com/hankki/core/datastore/TokenDataStoreImpl.kt
  core/datastore/src/main/java/com/hankki/core/datastore/di/SharedPreferenceModule.kt
  core/datastore/src/main/java/com/hankki/core/datastore/di/TokenDataStoreModule.kt
  data/login/.gitignore
  data/login/build.gradle.kts
  data/login/proguard-rules.pro
  data/login/src/androidTest/java/com/hankki/data/login/ExampleInstrumentedTest.kt
  data/login/src/main/AndroidManifest.xml
  data/login/src/main/java/com/hankki/data/login/datasource/LoginDataSource.kt
  data/login/src/main/java/com/hankki/data/login/datasourceImpl/LoginDataSourceImpl.kt
  data/login/src/main/java/com/hankki/data/login/di/DataSourceModule.kt
  data/login/src/main/java/com/hankki/data/login/di/LoginRepositoryModule.kt
  data/login/src/main/java/com/hankki/data/login/di/ServiceModule.kt
  data/login/src/main/java/com/hankki/data/login/dto/request/LoginRequestDto.kt
  data/login/src/main/java/com/hankki/data/login/dto/response/LoginResponseDto.kt
  data/login/src/main/java/com/hankki/data/login/repositoryImpl/LoginRepositoryImpl.kt
  data/login/src/main/java/com/hankki/data/login/service/LoginService.kt
  data/login/src/test/java/com/hankki/data/login/ExampleUnitTest.kt
  data/token/.gitignore
  data/token/build.gradle.kts
  data/token/proguard-rules.pro
  data/token/src/androidTest/java/com/hankki/data/token/ExampleInstrumentedTest.kt
  data/token/src/main/AndroidManifest.xml
  data/token/src/main/java/com/hankki/data/token/di/TokenRepositoryModule.kt
  data/token/src/main/java/com/hankki/data/token/repositoryImpl/TokenRepositoryImpl.kt
  data/token/src/test/java/com/hankki/data/token/ExampleUnitTest.kt
  domain/login/.gitignore
  domain/login/build.gradle.kts
  domain/login/src/main/java/com/hankki/domain/login/entity/request/LoginRequestEntity.kt
  domain/login/src/main/java/com/hankki/domain/login/entity/response/LoginResponseEntity.kt
  domain/login/src/main/java/com/hankki/domain/login/repository/LoginRepository.kt
  domain/token/.gitignore
  domain/token/build.gradle.kts
  domain/token/src/main/java/com/hankki/domain/token/repository/TokenRepository.kt
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginSideEffect.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginState.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginViewModel.kt
  feature/login/src/main/java/com/hankki/feature/login/navigation/LoginNavigation.kt
  feature/login/src/main/res/drawable/btn_kakao.xml
  feature/login/src/main/res/drawable/ic_android_black_24dp.xml
  feature/login/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: FEATURE ✨, 세영 🦌

#39 [Feature/#37] login context issue
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginViewModel.kt
Labels: FIX 🛠️

#41 [Add #40] add quit icon
  feature/my/src/main/java/com/hankki/feature/my/MyRoute.kt
  feature/my/src/main/res/drawable/ic_quit.xml
Labels: ADD ✚, 혜음 🥖

#42 [Feature/#33] report screen
  core/common/build.gradle.kts
  core/common/src/main/java/com/hankki/core/common/utill/ContentUriRequestBody.kt
  core/common/src/main/java/com/hankki/core/common/utill/Regex.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/AddPhotoButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiChipWithIcon.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/layout/BottomBlurLayout.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTitleTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/topappbar/HankkiTopBar.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_add_circle_dark_plus.xml
  core/designsystem/src/main/res/drawable/ic_arrow_down.xml
  core/designsystem/src/main/res/drawable/ic_arrow_left.xml
  core/designsystem/src/main/res/drawable/ic_arrow_up.xml
  core/designsystem/src/main/res/drawable/ic_check_btn.xml
  core/designsystem/src/main/res/drawable/ic_circle_x.xml
  core/designsystem/src/main/res/drawable/ic_drag_handle.xml
  core/designsystem/src/main/res/drawable/ic_dropdown_btn.xml
  core/designsystem/src/main/res/drawable/ic_ellipse.xml
  core/designsystem/src/main/res/drawable/ic_food.xml
  core/designsystem/src/main/res/drawable/ic_heart.xml
  core/designsystem/src/main/res/drawable/ic_map_here.xml
  core/designsystem/src/main/res/drawable/ic_plus_btn_empty.xml
  core/designsystem/src/main/res/drawable/ic_plus_btn_filled.xml
  core/designsystem/src/main/res/drawable/ic_x.xml
  domain/report/.gitignore
  domain/report/build.gradle.kts
  domain/report/src/main/java/com/hankki/domain/report/entity/CategoryEntity.kt
  domain/report/src/main/java/com/hankki/domain/report/entity/MenuEntity.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiTopBar.kt
  feature/home/src/main/java/com/hankki/feature/home/component/RepositionButton.kt
  feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/main/src/main/java/com/hankki/feature/main/MainTab.kt
  feature/report/build.gradle.kts
  feature/report/src/main/java/com/hankki/feature/report/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/ReportState.kt
  feature/report/src/main/java/com/hankki/feature/report/ReportViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/model/MenuModel.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  feature/report/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEATURE ✨, 동민 👻

#44 [Feature/#43] button touch effect & apply bottomNavigation Icon
  core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_home_selected.xml
  core/designsystem/src/main/res/drawable/ic_home_unselected.xml
  core/designsystem/src/main/res/drawable/ic_jaebo.xml
  core/designsystem/src/main/res/drawable/ic_my_selected.xml
  core/designsystem/src/main/res/drawable/ic_my_unselected.xml
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiStateChip.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/main/src/main/java/com/hankki/feature/main/MainTab.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
Labels: FEATURE ✨, 동민 👻

#48 [Fix/#46] home tag error
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiChipWithIcon.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiStateChip.kt
  feature/home/src/main/java/com/hankki/feature/home/model/ChipState.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  settings.gradle.kts
Labels: FIX 🛠️, 동민 👻

#50 [Feature/#45] report search store
  core/common/src/main/java/com/hankki/core/common/utill/UiState.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/layout/BlurLayout.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiSearchTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/topappbar/HankkiTopBar.kt
  core/designsystem/src/main/res/drawable/ic_circle_dark_x.xml
  core/designsystem/src/main/res/drawable/white_gradiend_bottom.xml
  core/designsystem/src/main/res/drawable/white_gradient.xml
  core/designsystem/src/main/res/drawable/white_gradient_top.xml
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/main/src/main/java/com/hankki/feature/main/MainTab.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportState.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/model/LocationModel.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreState.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/component/EmptyLocationView.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/component/LocationItem.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/component/LocationList.kt
  feature/report/src/main/res/drawable/img_empty.xml
  feature/report/src/main/res/values/strings.xml
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
Labels: FEATURE ✨, 동민 👻

#53 [Feature/#52] connect home with university
  core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
  feature/universityselection/src/main/res/values/strings.xml
Labels: FIX 🛠️, FEATURE ✨, 동민 👻

#55 [Feature/#51] report finish
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  core/designsystem/src/main/res/drawable/ic_add_red.xml
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishSideEffect.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishState.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/component/ReportFinishCard.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportSideEffect.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportState.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  feature/report/src/main/res/drawable/ic_launcher_background.xml
  feature/report/src/main/res/drawable/ic_launcher_foreground.xml
  feature/report/src/main/res/drawable/img_store.xml
  feature/report/src/main/res/drawable/img_white_long_bottom_gradient.png
  feature/report/src/main/res/drawable/img_yellow_circle_gradient.png
  feature/report/src/main/res/values/strings.xml
Labels: FEATURE ✨, 동민 👻

#38 [Feature/#26] my jogbo
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/DialogWithDescription.kt
  core/designsystem/src/main/res/drawable/ic_heart_filled.xml
  domain/my/src/main/java/com/hankki/domain/my/entity/MyJogboDetailEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/MyJogboEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/StoreEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/UserInformationEntity.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/my/src/main/java/com/hankki/feature/my/component/AddJogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/component/ButtonWithImageAndBorder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/DialogWithButton.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboHashtagChip.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboItemText.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboShareButton.kt
  feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
  feature/my/src/main/java/com/hankki/feature/my/component/Title.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/model/MyJogboModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyState.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
  feature/my/src/main/res/drawable/ic_add.xml
  feature/my/src/main/res/drawable/ic_add_jogbo.xml
  feature/my/src/main/res/drawable/ic_add_jogbo_disable.xml
  feature/my/src/main/res/drawable/ic_my_jogbo_fold.xml
  feature/my/src/main/res/drawable/ic_my_store.xml
  feature/my/src/main/res/drawable/ic_share.xml
  feature/my/src/main/res/drawable/ic_spoon.xml
  feature/my/src/main/res/values/strings.xml
Labels: UI 📱, 혜음 🥖

#60 [Feature/#54] my store
  domain/my/src/main/java/com/hankki/domain/my/entity/StoreEntity.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreState.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/model/MyStoreModel.kt
  feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
Labels: UI 📱, 혜음 🥖

#63 [Fix/#58] text line height error
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Type.kt
Labels: FIX 🛠️, 동민 👻

#56 [Feature/#49] store detail
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/bottomsheet/HankkiStoreJogboBottomSheet.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreDetailButton.kt
  core/designsystem/src/main/res/drawable/ic_add_circle_dark_plus.xml
  core/designsystem/src/main/res/drawable/ic_add_photo_alternate.xml
  core/designsystem/src/main/res/drawable/ic_arrow_back.xml
  core/designsystem/src/main/res/drawable/ic_arrow_down.xml
  core/designsystem/src/main/res/drawable/ic_arrow_left.xml
  core/designsystem/src/main/res/drawable/ic_circle_dark_x.xml
  core/designsystem/src/main/res/drawable/ic_circle_x.xml
  core/designsystem/src/main/res/drawable/ic_drag_handle.xml
  core/designsystem/src/main/res/drawable/ic_home_selected.xml
  core/designsystem/src/main/res/drawable/ic_home_unselected.xml
  core/designsystem/src/main/res/drawable/ic_jaebo.xml
  core/designsystem/src/main/res/drawable/ic_like.xml
  core/designsystem/src/main/res/drawable/ic_my_selected.xml
  core/designsystem/src/main/res/drawable/ic_my_unselected.xml
  core/designsystem/src/main/res/drawable/ic_red_like.xml
  core/designsystem/src/main/res/drawable/ic_search.xml
  core/designsystem/src/main/res/drawable/ic_uncheck_btn.xml
  core/designsystem/src/main/res/drawable/img_black_gradient_top.xml
  core/designsystem/src/main/res/drawable/white_gradient_top.xml
  core/designsystem/src/main/res/values/string.xml
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hankki/feature/main/MainActivity.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/main/src/main/res/drawable/img_logo.xml
  feature/main/src/main/res/drawable/img_subtitle.xml
  feature/main/src/main/res/drawable/img_title.xml
  feature/my/src/main/res/drawable/ic_add.xml
  feature/my/src/main/res/drawable/ic_add_jogbo.xml
  feature/my/src/main/res/drawable/ic_add_jogbo_disable.xml
  feature/my/src/main/res/drawable/ic_my_jogbo_fold.xml
  feature/my/src/main/res/drawable/ic_my_store.xml
  feature/my/src/main/res/drawable/ic_share.xml
  feature/my/src/main/res/drawable/ic_spoon.xml
  feature/report/src/main/res/drawable/img_empty.xml
  feature/report/src/main/res/drawable/img_store.xml
  feature/storedetail/.gitignore
  feature/storedetail/build.gradle.kts
  feature/storedetail/proguard-rules.pro
  feature/storedetail/src/androidTest/java/com/hankki/feature/storedetail/ExampleInstrumentedTest.kt
  feature/storedetail/src/main/AndroidManifest.xml
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreState.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailBox.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailItem.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/model/MenuItem.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/navigateStoreDetail.kt
  feature/storedetail/src/main/res/drawable/img_default_store_detail.xml
  feature/storedetail/src/main/res/values/strings.xml
  feature/storedetail/src/test/java/com/hankki/feature/storedetail/ExampleUnitTest.kt
  settings.gradle.kts
Labels: UI 📱, 세영 🦌

#65 [Feature #64] feat home filters
  app/build.gradle.kts
  data/home/.gitignore
  data/home/build.gradle.kts
  data/home/consumer-rules.pro
  data/home/proguard-rules.pro
  data/home/src/androidTest/java/com/hankki/data/home/ExampleInstrumentedTest.kt
  data/home/src/main/AndroidManifest.xml
  data/home/src/main/java/com/hankki/data/home/datasource/HomeDataSource.kt
  data/home/src/main/java/com/hankki/data/home/datasourcimpl/HomeDataSourceImpl.kt
  data/home/src/main/java/com/hankki/data/home/di/DataSourceModule.kt
  data/home/src/main/java/com/hankki/data/home/di/RepositoryModule.kt
  data/home/src/main/java/com/hankki/data/home/di/ServiceModule.kt
  data/home/src/main/java/com/hankki/data/home/dto/CategoryDto.kt
  data/home/src/main/java/com/hankki/data/home/dto/PriceCategoriesDto.kt
  data/home/src/main/java/com/hankki/data/home/dto/SortCategoriesDto.kt
  data/home/src/main/java/com/hankki/data/home/repositoryImpl/HomeRepositoryImpl.kt
  data/home/src/main/java/com/hankki/data/home/service/HomeService.kt
  data/home/src/test/java/com/hankki/data/home/ExampleUnitTest.kt
  domain/home/.gitignore
  domain/home/build.gradle.kts
  domain/home/src/main/java/com/hankki/domain/home/entity/response/CategoriesEntity.kt
  domain/home/src/main/java/com/hankki/domain/home/entity/response/CategoryEntity.kt
  domain/home/src/main/java/com/hankki/domain/home/repository/HomeRepository.kt
  feature/home/build.gradle.kts
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
  feature/home/src/main/java/com/hankki/feature/home/model/PriceChipItem.kt
  settings.gradle.kts
Labels: FEATURE ✨, 동민 👻

#67 [Feature/#57] store detail api
  app/build.gradle.kts
  data/reissuetoken/build.gradle.kts
  data/storedetail/.gitignore
  data/storedetail/build.gradle.kts
  data/storedetail/proguard-rules.pro
  data/storedetail/src/androidTest/java/com/hankki/data/storedetail/ExampleInstrumentedTest.kt
  data/storedetail/src/main/AndroidManifest.xml
  data/storedetail/src/main/java/com/hankki/data/storedetail/datasource/StoreDetailDataSource.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/datasourceImpl/StoreDetailDataSourceImpl.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/di/DataSourceModule.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/di/RepositoryModule.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/di/ServiceModule.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/repositoryImpl/StoreDetailRepositoryImpl.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/response/StoreDetailResponseDto.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/service/StoreDetailService.kt
  data/storedetail/src/test/java/com/hankki/data/storedetail/ExampleUnitTest.kt
  domain/storedetail/.gitignore
  domain/storedetail/build.gradle.kts
  domain/storedetail/src/main/java/com/hankki/domain/storedetail/entity/StoreDetailResponseEntity.kt
  domain/storedetail/src/main/java/com/hankki/domain/storedetail/repository/StoreDetailRepository.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/storedetail/build.gradle.kts
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreState.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailBox.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/navigation/navigateStoreDetail.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: FEATURE ✨, 세영 🦌

#69 [Feature/#66] store search api
  app/build.gradle.kts
  data/report/.gitignore
  data/report/build.gradle.kts
  data/report/consumer-rules.pro
  data/report/proguard-rules.pro
  data/report/src/androidTest/java/com/hankki/data/report/ExampleInstrumentedTest.kt
  data/report/src/main/AndroidManifest.xml
  data/report/src/main/java/com/hankki/data/report/datasource/ReportDataSource.kt
  data/report/src/main/java/com/hankki/data/report/datasourceimpl/ReportDataSourceImpl.kt
  data/report/src/main/java/com/hankki/data/report/di/DataSourceModule.kt
  data/report/src/main/java/com/hankki/data/report/di/RepositoryModule.kt
  data/report/src/main/java/com/hankki/data/report/di/ServiceModule.kt
  data/report/src/main/java/com/hankki/data/report/dto/LocationsResponseDto.kt
  data/report/src/main/java/com/hankki/data/report/repositoryimpl/ReportRepositoryImpl.kt
  data/report/src/main/java/com/hankki/data/report/service/ReportService.kt
  data/report/src/test/java/com/hankki/data/report/ExampleUnitTest.kt
  domain/report/src/main/java/com/hankki/domain/report/entity/LocationEntity.kt
  domain/report/src/main/java/com/hankki/domain/report/repository/ReportRepository.kt
  feature/report/src/main/java/com/hankki/feature/report/model/LocationModel.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreState.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreViewModel.kt
  settings.gradle.kts
Labels: FEATURE ✨, 동민 👻

#72 [Feature/#71] report count api
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
  data/report/src/main/java/com/hankki/data/report/datasource/ReportDataSource.kt
  data/report/src/main/java/com/hankki/data/report/datasourceimpl/ReportDataSourceImpl.kt
  data/report/src/main/java/com/hankki/data/report/dto/response/CountResponseDto.kt
  data/report/src/main/java/com/hankki/data/report/dto/response/LocationsResponseDto.kt
  data/report/src/main/java/com/hankki/data/report/repositoryimpl/ReportRepositoryImpl.kt
  data/report/src/main/java/com/hankki/data/report/service/ReportService.kt
  domain/report/src/main/java/com/hankki/domain/report/entity/CountEntity.kt
  domain/report/src/main/java/com/hankki/domain/report/repository/ReportRepository.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  feature/report/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: FEATURE ✨, 동민 👻

#75 [Feature/#74] get user university
  data/home/src/main/java/com/hankki/data/home/datasource/HomeDataSource.kt
  data/home/src/main/java/com/hankki/data/home/datasourcimpl/HomeDataSourceImpl.kt
  data/home/src/main/java/com/hankki/data/home/dto/response/UniversityResponseDto.kt
  data/home/src/main/java/com/hankki/data/home/repositoryImpl/HomeRepositoryImpl.kt
  data/home/src/main/java/com/hankki/data/home/service/HomeService.kt
  domain/home/src/main/java/com/hankki/domain/home/entity/response/UniversityResponseEntity.kt
  domain/home/src/main/java/com/hankki/domain/home/repository/HomeRepository.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/model/UniversityModel.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
Labels: FEATURE ✨, 동민 👻

#76 [Feature/#62] my new jogbo
  core/common/src/main/java/com/hankki/core/common/utill/Regex.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiCountTextField.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboViewModel.kt
  feature/my/src/main/res/values/strings.xml
Labels: UI 📱, 혜음 🥖

#81 [Feature/#80] dialog designsystem
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/DoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/ImageDoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/SingleButtonDialog.kt
  core/designsystem/src/main/res/drawable/img_charactor.xml
Labels: FEATURE ✨, 동민 👻

#79 [Feature/#73] validate store
  core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/DoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/SingleButtonDialog.kt
  core/network/src/main/java/com/hankki/core/network/CreatedBaseResponse.kt
  data/report/src/main/java/com/hankki/data/report/datasource/ReportDataSource.kt
  data/report/src/main/java/com/hankki/data/report/datasourceimpl/ReportDataSourceImpl.kt
  data/report/src/main/java/com/hankki/data/report/dto/request/ValidateStoreRequestDto.kt
  data/report/src/main/java/com/hankki/data/report/repositoryimpl/ReportRepositoryImpl.kt
  data/report/src/main/java/com/hankki/data/report/service/ReportService.kt
  domain/report/src/main/java/com/hankki/domain/report/entity/request/ValidateStoreRequestEntity.kt
  domain/report/src/main/java/com/hankki/domain/report/repository/ReportRepository.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreSideEffect.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreState.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreViewModel.kt
Labels: FEATURE ✨, 동민 👻

#77 [Feature/#68] university selection api
  app/build.gradle.kts
  data/storedetail/src/main/java/com/hankki/data/storedetail/di/RepositoryModule.kt
  data/universityselection/.gitignore
  data/universityselection/build.gradle.kts
  data/universityselection/proguard-rules.pro
  data/universityselection/src/androidTest/java/com/hankki/data/universityselection/ExampleInstrumentedTest.kt
  data/universityselection/src/main/AndroidManifest.xml
  data/universityselection/src/main/java/com/hankki/data/universityselection/datasource/UniversitySelectionDataSource.kt
  data/universityselection/src/main/java/com/hankki/data/universityselection/datasourceImpl/UniversirySelectionDataSourceImpl.kt
  data/universityselection/src/main/java/com/hankki/data/universityselection/dto/DataSourceModule.kt
  data/universityselection/src/main/java/com/hankki/data/universityselection/dto/RepositoryModule.kt
  data/universityselection/src/main/java/com/hankki/data/universityselection/dto/ServiceModule.kt
  data/universityselection/src/main/java/com/hankki/data/universityselection/dto/request/UniversitySelectionRequestDto.kt
  data/universityselection/src/main/java/com/hankki/data/universityselection/dto/response/UniversitySelectionResponseDto.kt
  data/universityselection/src/main/java/com/hankki/data/universityselection/repositoryImpl/UniversitySelectionRepositoryImpl.kt
  data/universityselection/src/main/java/com/hankki/data/universityselection/service/UniversitySelectionService.kt
  data/universityselection/src/test/java/com/hankki/data/universityselection/ExampleUnitTest.kt
  domain/universityselection/src/main/java/com/hankki/domain/universityselection/UniversitySelectionModel.kt
  domain/universityselection/src/main/java/com/hankki/domain/universityselection/entity/UniversitySelectionEntity.kt
  domain/universityselection/src/main/java/com/hankki/domain/universityselection/entity/UniversitySelectionRequest.kt
  domain/universityselection/src/main/java/com/hankki/domain/universityselection/repository/UniversitySelectionRepository.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionSideEffect.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionState.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionViewModel.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/component/UniversityItem.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/navigation/UniversitySelectionNavigation.kt
  settings.gradle.kts
Labels: FEATURE ✨, 세영 🦌

#85 [Feature/#84] my information api
  app/build.gradle.kts
  data/my/.gitignore
  data/my/build.gradle.kts
  data/my/consumer-rules.pro
  data/my/proguard-rules.pro
  data/my/src/androidTest/java/com/hankki/data/my/ExampleInstrumentedTest.kt
  data/my/src/main/AndroidManifest.xml
  data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
  data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
  data/my/src/main/java/com/hankki/data/my/di/DataSourceModule.kt
  data/my/src/main/java/com/hankki/data/my/di/RepositoryModule.kt
  data/my/src/main/java/com/hankki/data/my/di/ServiceModule.kt
  data/my/src/main/java/com/hankki/data/my/dto/response/UserInformationDto.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  data/my/src/main/java/com/hankki/data/my/service/MyService.kt
  data/my/src/test/java/com/hankki/data/my/ExampleUnitTest.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/MyRepository.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/UserInfoEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/UserInformationEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/MyJogboDetailEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/MyJogboEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/StoreEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/UserInformationEntity.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/model/MyJogboModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyState.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/model/MyModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/model/MyStoreModel.kt
  feature/my/src/main/res/drawable/ic_my_graphic.xml
  feature/my/src/main/res/drawable/ic_mygraphic.xml
  settings.gradle.kts
Labels: FEATURE ✨, 혜음 🥖

#87 [Feature/#86] my connect link
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyState.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
  feature/my/src/main/res/values/strings.xml
Labels: FEATURE ✨, 혜음 🥖

#93 [Feature/#91] my page dialog
  data/my/src/main/java/com/hankki/data/my/di/RepositoryModule.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
  feature/my/src/main/java/com/hankki/feature/my/component/DialogWithButton.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyState.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/my/src/main/res/values/strings.xml
Labels: UI 📱, 혜음 🥖

#96 [Feature/#95] my jogbo api
  data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
  data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
  data/my/src/main/java/com/hankki/data/my/dto/response/MyJogboDto.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  data/my/src/main/java/com/hankki/data/my/service/MyService.kt
  domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/model/MyJogboModel.kt
  feature/my/src/main/res/drawable/img_list_0.xml
  feature/my/src/main/res/drawable/img_list_1.xml
  feature/my/src/main/res/drawable/img_list_2.xml
  feature/my/src/main/res/drawable/img_list_3.xml
Labels: FEATURE ✨, 혜음 🥖

#92 [Feature/#90] home list check
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/bottomsheet/HankkiStoreJogboBottomSheet.kt
  core/designsystem/src/main/res/drawable/ic_jogbo_type_four.xml
  core/designsystem/src/main/res/drawable/ic_jogbo_type_one.xml
  core/designsystem/src/main/res/drawable/ic_jogbo_type_three.xml
  core/designsystem/src/main/res/drawable/ic_jogbo_type_two.xml
  data/home/src/main/java/com/hankki/data/home/datasource/HomeDataSource.kt
  data/home/src/main/java/com/hankki/data/home/datasourcimpl/HomeDataSourceImpl.kt
  data/home/src/main/java/com/hankki/data/home/dto/response/FavoritesResponseDto.kt
  data/home/src/main/java/com/hankki/data/home/dto/response/StoreThumbnailResponseDto.kt
  data/home/src/main/java/com/hankki/data/home/dto/response/StoresPinsDto.kt
  data/home/src/main/java/com/hankki/data/home/dto/response/StoresResponseDto.kt
  data/home/src/main/java/com/hankki/data/home/repositoryImpl/HomeRepositoryImpl.kt
  data/home/src/main/java/com/hankki/data/home/service/HomeService.kt
  domain/home/src/main/java/com/hankki/domain/home/entity/response/JogboResponseEntity.kt
  domain/home/src/main/java/com/hankki/domain/home/entity/response/StoreEntity.kt
  domain/home/src/main/java/com/hankki/domain/home/entity/response/StorePinEntity.kt
  domain/home/src/main/java/com/hankki/domain/home/repository/HomeRepository.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
  feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
  feature/home/src/main/java/com/hankki/feature/home/model/ChipState.kt
  feature/home/src/main/java/com/hankki/feature/home/model/PinModel.kt
  feature/home/src/main/java/com/hankki/feature/home/model/StoreItemEntity.kt
  feature/home/src/main/java/com/hankki/feature/home/model/StoreItemModel.kt
  feature/home/src/main/java/com/hankki/feature/home/model/UniversityModel.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
Labels: FEATURE ✨, 동민 👻

#104 [Feature/#103] delete dummy
  app/build.gradle.kts
  data/dummy/.gitignore
  data/dummy/build.gradle.kts
  data/dummy/consumer-rules.pro
  data/dummy/src/main/AndroidManifest.xml
  data/dummy/src/main/java/com/hankki/data/dummy/datasource/ReqresDataSource.kt
  data/dummy/src/main/java/com/hankki/data/dummy/datasourceimpl/ReqresDataSourceImpl.kt
  data/dummy/src/main/java/com/hankki/data/dummy/di/DataSourceModule.kt
  data/dummy/src/main/java/com/hankki/data/dummy/di/RepositoryModule.kt
  data/dummy/src/main/java/com/hankki/data/dummy/di/ServiceModule.kt
  data/dummy/src/main/java/com/hankki/data/dummy/dto/RequreUserList.kt
  data/dummy/src/main/java/com/hankki/data/dummy/repositoryimpl/ReqresRepositoryImpl.kt
  data/dummy/src/main/java/com/hankki/data/dummy/service/ReqresService.kt
  data/dummy/src/test/java/com/hankki/data/dummy/ExampleUnitTest.kt
  domain/dummy/.gitignore
  domain/dummy/build.gradle.kts
  domain/dummy/src/main/java/com/hankki/domain/dummy/entity/response/ReqresUserModel.kt
  domain/dummy/src/main/java/com/hankki/domain/dummy/repository/ReqresRepository.kt
  feature/dummy/.gitignore
  feature/dummy/build.gradle.kts
  feature/dummy/consumer-rules.pro
  feature/dummy/src/androidTest/java/com/hankki/feature/dummy/ExampleInstrumentedTest.kt
  feature/dummy/src/main/AndroidManifest.xml
  feature/dummy/src/main/java/com/hankki/feature/dummy/DummyRoute.kt
  feature/dummy/src/main/java/com/hankki/feature/dummy/DummySideEffect.kt
  feature/dummy/src/main/java/com/hankki/feature/dummy/DummyState.kt
  feature/dummy/src/main/java/com/hankki/feature/dummy/DummyViewModel.kt
  feature/dummy/src/main/java/com/hankki/feature/dummy/navigation/DummyNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  settings.gradle.kts
Labels: FEATURE ✨, 동민 👻

#102 [Feature/#98] add store at jogbo
  core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/bottomsheet/HankkiStoreJogboBottomSheet.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/AddPhotoButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreNameSearchButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiChipWithIcon.kt
  data/home/src/main/java/com/hankki/data/home/datasource/HomeDataSource.kt
  data/home/src/main/java/com/hankki/data/home/datasourcimpl/HomeDataSourceImpl.kt
  data/home/src/main/java/com/hankki/data/home/repositoryImpl/HomeRepositoryImpl.kt
  data/home/src/main/java/com/hankki/data/home/service/HomeService.kt
  domain/home/src/main/java/com/hankki/domain/home/repository/HomeRepository.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
Labels: FEATURE ✨, 동민 👻

#99 [Feature/#97] create jogbo
  data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
  data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
  data/my/src/main/java/com/hankki/data/my/dto/request/NewJogboDto.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  data/my/src/main/java/com/hankki/data/my/service/MyService.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/request/NewJogboEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboSideEffect.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboViewModel.kt
Labels: FEATURE ✨, 혜음 🥖

#101 [Feature #94] MySideEffect
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/model/MySideEffect.kt
Labels: FIX 🛠️, 혜음 🥖

#109 [Feature/#88] onboarding
  core/common/src/main/java/com/hankki/core/common/utill/SystemBarColorChanger.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/OnboardingRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/navigation/LoginNavigation.kt
  feature/login/src/main/java/com/hankki/feature/login/navigation/OnboardingNavigation.kt
  feature/login/src/main/res/drawable/login.xml
  feature/login/src/main/res/raw/step1.json
  feature/login/src/main/res/raw/step2.json
  feature/login/src/main/res/raw/step3.json
  feature/login/src/main/res/raw/step4.json
  feature/login/src/main/res/values/strings.xml
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  gradle/libs.versions.toml
Labels: UI 📱, 세영 🦌

#106 [Docs/#105]Update README
  README.md
Labels: DOCS 📝, 동민 👻

#113 [Feature/#108] user related store api
  data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
  data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
  data/my/src/main/java/com/hankki/data/my/dto/response/StoreDto.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  data/my/src/main/java/com/hankki/data/my/service/MyService.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/StoreEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/model/MyStoreModel.kt
Labels: FEATURE ✨, 혜음 🥖

#118 [Feature/#114] jogbo detail api
  data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
  data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
  data/my/src/main/java/com/hankki/data/my/dto/response/JogboDetailDto.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  data/my/src/main/java/com/hankki/data/my/service/MyService.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/MyJogboDetailEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
Labels: FEATURE ✨, 혜음 🥖

#115 [Feature/#110] logout api
  data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
  data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  data/my/src/main/java/com/hankki/data/my/service/MyService.kt
  domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
  feature/my/build.gradle.kts
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/model/MySideEffect.kt
Labels: FEATURE ✨, 세영 🦌

#116 [Feature/#112] delete withdraw
  data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
  data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  data/my/src/main/java/com/hankki/data/my/service/MyService.kt
  domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/model/MySideEffect.kt
Labels: FEATURE ✨, 세영 🦌

#117 [Feature/#107] detail work
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/bottomsheet/HankkiStoreJogboBottomSheet.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/HankkiButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/DoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/ImageDoubleButtonDialog.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Theme.kt
  core/designsystem/src/main/res/drawable/ic_food_my_plus.xml
  data/storedetail/src/main/java/com/hankki/data/storedetail/datasource/StoreDetailDataSource.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/datasourceImpl/StoreDetailDataSourceImpl.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/repositoryImpl/StoreDetailRepositoryImpl.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/response/FavoritesResponseDto.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/service/StoreDetailService.kt
  domain/storedetail/src/main/java/com/hankki/domain/storedetail/entity/JogboResponseEntity.kt
  domain/storedetail/src/main/java/com/hankki/domain/storedetail/repository/StoreDetailRepository.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/login/build.gradle.kts
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/OnboardingRoute.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreState.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/navigation/navigateStoreDetail.kt
  gradle/libs.versions.toml
Labels: FEATURE ✨, 동민 👻

#120 [Feature/#111] splash navigation
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Theme.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/hankki/feature/main/MainActivity.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/main/src/main/java/com/hankki/feature/main/MainTab.kt
  feature/main/src/main/java/com/hankki/feature/main/splash/SplashScreen.kt
  feature/main/src/main/java/com/hankki/feature/main/splash/SplashSideEffect.kt
  feature/main/src/main/java/com/hankki/feature/main/splash/SplashViewModel.kt
  feature/main/src/main/java/com/hankki/feature/main/splash/navigation/SplashNavigation.kt
Labels: FEATURE ✨, 동민 👻

#121 [Feature/#119] jogbo store delete api
  data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
  data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
  data/my/src/main/java/com/hankki/data/my/dto/request/JogbosRequestDto.kt
  data/my/src/main/java/com/hankki/data/my/dto/response/LikedStoreResponseDto.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  data/my/src/main/java/com/hankki/data/my/service/MyService.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/LikedStoreResponseEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboSideEffect.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreSideEffect.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
Labels: FEATURE ✨, 혜음 🥖

#124 [Feature/#123] store detail onboarding
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/ImageDoubleButtonDialog.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/datasource/StoreDetailDataSource.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/datasourceImpl/StoreDetailDataSourceImpl.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/repositoryImpl/StoreDetailRepositoryImpl.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/response/StoreDetailNicknameResponseDto.kt
  data/storedetail/src/main/java/com/hankki/data/storedetail/service/StoreDetailService.kt
  domain/storedetail/src/main/java/com/hankki/domain/storedetail/entity/StoreDetailNicknameEntity.kt
  domain/storedetail/src/main/java/com/hankki/domain/storedetail/repository/StoreDetailRepository.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginSideEffect.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginViewModel.kt
  feature/login/src/main/java/com/hankki/feature/login/navigation/LoginNavigation.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailDialogState.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreState.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailBox.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailItem.kt
Labels: UI 📱, FEATURE ✨, 세영 🦌

#125 [Feature/#122] detail works
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/component/SelectedImageController.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
Labels: FEATURE ✨, 동민 👻

#126 [Feature #100] fix phoenix
  core/network/src/main/java/com/hankki/core/network/OauthInterceptor.kt
  data/reissuetoken/src/main/java/com/hankki/data/reissuetoken/datasource/ReissueTokenDataSource.kt
  data/reissuetoken/src/main/java/com/hankki/data/reissuetoken/datasourceImpl/ReissueTokenDataSourceImpl.kt
  data/reissuetoken/src/main/java/com/hankki/data/reissuetoken/repositoryImpl/ReissueTokenRepositoryImpl.kt
  data/reissuetoken/src/main/java/com/hankki/data/reissuetoken/service/ReissueTokenService.kt
  domain/reissuetoken/src/main/java/com/hankki/domain/reissuetoken/repository/ReissueTokenRepository.kt
Labels: FIX 🛠️, 세영 🦌

#130 [Feature #129] getUserName to JogboDetail
  feature/my/src/main/java/com/hankki/feature/my/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/res/drawable/user_image.xml
Labels: FEATURE ✨, 혜음 🥖

#132 [Feature/#128] 1st qa
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/bottomsheet/HankkiStoreJogboBottomSheet.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/AddPhotoButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTitleTextField.kt
  core/designsystem/src/main/res/drawable/ic_food.xml
  core/designsystem/src/main/res/values/string.xml
  data/report/src/main/java/com/hankki/data/report/datasource/ReportDataSource.kt
  data/report/src/main/java/com/hankki/data/report/datasourceimpl/ReportDataSourceImpl.kt
  data/report/src/main/java/com/hankki/data/report/dto/response/FavoritesResponseDto.kt
  data/report/src/main/java/com/hankki/data/report/dto/response/StoreDetailNicknameResponseDto.kt
  data/report/src/main/java/com/hankki/data/report/repositoryimpl/ReportRepositoryImpl.kt
  data/report/src/main/java/com/hankki/data/report/service/ReportService.kt
  domain/report/src/main/java/com/hankki/domain/report/entity/response/JogboResponseEntity.kt
  domain/report/src/main/java/com/hankki/domain/report/entity/response/UserInfoResponseEntity.kt
  domain/report/src/main/java/com/hankki/domain/report/repository/ReportRepository.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishState.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/main/component/SelectedImageController.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  feature/report/src/main/res/values/strings.xml
  feature/storedetail/build.gradle.kts
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/navigation/navigateStoreDetail.kt
Labels: FIX 🛠️, UI 📱, FEATURE ✨, 동민 👻

#133 [Feature/#127] 1차 QA
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreDetailButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/dialog/ImageDoubleButtonDialog.kt
  core/designsystem/src/main/res/drawable/ic_btn_add_my_jogbo.xml
  core/designsystem/src/main/res/drawable/ic_btn_radio_check.xml
  core/designsystem/src/main/res/drawable/ic_btn_radio_uncheck.xml
  core/designsystem/src/main/res/drawable/img_black_gradation_top.xml
  feature/login/src/main/java/com/hankki/feature/login/OnboardingRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/navigation/OnboardingNavigation.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailBox.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/navigation/UniversitySelectionNavigation.kt
Labels: FIX 🛠️, 세영 🦌

#138 [Feature/#137] 2nd qa
  feature/home/src/main/java/com/hankki/feature/home/component/StoreItem.kt
Labels: FEATURE ✨, 동민 👻
