Repository Team-Hankki/hankki-android, pull requests merged in 2024-10, with the labels that each got.

#246 [Feature/#245] mypage redesign
  feature/my/src/main/java/com/hankki/feature/my/component/StoreItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/component/AddJogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/component/JogboItem.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/JogboShareButton.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/MoveToHomeButton.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/component/ArrowIconButton.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/component/IconButton.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/component/ImageAndBorderButton.kt
  feature/my/src/main/java/com/hankki/feature/my/mystore/MyStoreRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
  feature/my/src/main/res/drawable/ic_arrow_right.xml
  feature/my/src/main/res/drawable/ic_my_graphic.xml
  feature/my/src/main/res/drawable/ic_myheart.xml
  feature/my/src/main/res/drawable/ic_myjokbo.xml
  feature/my/src/main/res/drawable/ic_newjaebo.xml
  feature/my/src/main/res/drawable/icon_back.xml
  feature/my/src/main/res/drawable/img_user_profile.xml
  feature/my/src/main/res/values/strings.xml
Labels: FIX 🛠️, UI 📱, 혜음 🥖

#251 [Docs #250] Change PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: DOCS 📝, 동민 👻

#249 [Feature/#248] redesign home
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/textfield/HankkiTitleTextField.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/topappbar/HankkiTopBar.kt
  core/designsystem/src/main/res/drawable/ic_arrow_up.xml
  core/designsystem/src/main/res/drawable/ic_home_selected.xml
  core/designsystem/src/main/res/drawable/ic_home_unselected.xml
  core/designsystem/src/main/res/drawable/ic_jaebo.xml
  core/designsystem/src/main/res/drawable/ic_marker.xml
  core/designsystem/src/main/res/drawable/ic_my_selected.xml
  core/designsystem/src/main/res/drawable/ic_my_unselected.xml
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiStateChip.kt
  feature/home/src/main/java/com/hankki/feature/home/model/ChipState.kt
  feature/home/src/main/res/drawable/ic_arrow_down_16.xml
  feature/home/src/main/res/drawable/ic_arrow_down_18.xml
  feature/home/src/main/res/drawable/ic_arrow_up_18.xml
  feature/home/src/main/res/drawable/ic_coin.xml
  feature/home/src/main/res/drawable/ic_empty_bowl.xml
  feature/home/src/main/res/drawable/ic_marker.xml
  feature/home/src/main/res/drawable/ic_sort.xml
  feature/home/src/main/res/drawable/ic_university.xml
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/main/src/main/java/com/hankki/feature/main/MainTab.kt
  feature/main/src/main/res/drawable/ic_home_selected.xml
  feature/main/src/main/res/drawable/ic_home_unselected.xml
  feature/main/src/main/res/drawable/ic_jaebo_selected.xml
  feature/main/src/main/res/drawable/ic_jaebo_unselected.xml
  feature/main/src/main/res/drawable/ic_profile_selected.xml
  feature/main/src/main/res/drawable/ic_profile_unselected.xml
Labels: REFACTOR ♻️, UI 📱, 동민 👻

#253 [Fix #252] fix university selection error
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
Labels: FIX 🛠️, 동민 👻

#258 Hotfix 반영
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  gradle/libs.versions.toml
Labels: HOTFIX 🚑, 동민 👻

#260 [Feature/#259] divide debug release app
  .gitignore
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/dev_ic_launcher-playstore.png
  app/src/main/res/drawable/dev_ic_launcher_background.xml
  app/src/main/res/drawable/dev_ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/dev_ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/dev_ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/dev_ic_launcher.webp
  app/src/main/res/mipmap-hdpi/dev_ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/dev_ic_launcher.webp
  app/src/main/res/mipmap-mdpi/dev_ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/dev_ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/dev_ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/dev_ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/dev_ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/dev_ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/dev_ic_launcher_round.webp
  app/src/main/res/values/strings.xml
Labels: FEATURE ✨, 동민 👻
