Repository Team-Hankki/hankki-android, pull requests merged in 2024-12, with the labels that each got.

#271 [Feature/#270] SnackBar의 prop drilling issue를 해결하고, 사용성을 개선합니다.
  app/build.gradle.kts
  build-logic/src/main/java/hankki.android.data.gradle.kts
  core/designsystem/src/main/java/com/hankki/core/designsystem/event/SnackBarTrigger.kt
  core/network/build.gradle.kts
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/navigation/HomeNavigation.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/report/src/main/java/com/hankki/feature/report/finish/ReportFinishRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/navigation/ReportNavigation.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/addmenu/AddMenuRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/delete/DeleteSuccessLastRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/delete/DeleteSuccessRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/editmenu/EditMenuRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/mod/ModRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/navigation/navigateStoreDetail.kt
  gradle/libs.versions.toml
Labels: FEATURE ✨, 동민 👻

#276 [Feature/#275] android version 15를 대응합니다.
  baselineprofile/build.gradle.kts
  core/common/src/main/java/com/hankki/core/common/utill/SystemBarColorChanger.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Theme.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: REFACTOR ♻️, 동민 👻

#281 [Feature/#277] store detail UI
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/button/StoreDetailButton.kt
  core/designsystem/src/main/java/com/hankki/core/designsystem/theme/Type.kt
  core/designsystem/src/main/res/drawable/ic_heart.xml
  core/designsystem/src/main/res/drawable/ic_home.xml
  core/designsystem/src/main/res/drawable/ic_my_jogbo.xml
  core/designsystem/src/main/res/drawable/ic_read_heart.xml
  core/designsystem/src/main/res/values/string.xml
  data/storedetail/src/main/java/com/hankki/data/storedetail/response/StoreDetailResponseDto.kt
  domain/storedetail/src/main/java/com/hankki/domain/storedetail/entity/StoreDetailResponseEntity.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/storedetail/build.gradle.kts
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailReportRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailState.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailViewModel.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailButton.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailHeadBox.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailItem.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailMapBox.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailMenuBox.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/navigation/navigateStoreDetail.kt
  feature/storedetail/src/main/res/drawable/ic_like.xml
  feature/storedetail/src/main/res/drawable/ic_map_error.xml
  feature/storedetail/src/main/res/drawable/ic_map_marker.xml
  feature/storedetail/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: UI 📱, FEATURE ✨
