Repository Team-Hankki/hankki-android, pull requests merged in 2025-03, with the labels that each got.

#301 [Feature/#300] Attach Amplitude
  core/common/src/main/java/com/hankki/core/common/amplitude/AmplitudeManager.kt
  core/common/src/main/java/com/hankki/core/common/amplitude/EventType.kt
  core/common/src/main/java/com/hankki/core/common/amplitude/PropertyKey.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiCatetoryScrollableTabRow.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterBottomSheet.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/JogboHeader.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportSideEffect.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportViewModel.kt
  feature/report/src/main/java/com/hankki/feature/report/searchstore/SearchStoreRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/add/addmenu/AddMenuRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/editmenu/EditMenuRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/editbottomsheet/edit/mod/ModRoute.kt
  feature/universityselection/src/main/java/com/hankki/feature/universityselection/UniversitySelectionRoute.kt
Labels: FEATURE ✨, 혜음 🥖

#296 [Feature/#291] storedetail qa
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailReportRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/StoreDetailRoute.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailButton.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailHeadBox.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailItem.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailMapBox.kt
  feature/storedetail/src/main/java/com/hankki/feature/storedetail/component/StoreDetailMenuBox.kt
  feature/storedetail/src/main/res/drawable/ic_arrow_down.xml
  feature/storedetail/src/main/res/drawable/ic_bottom_edit.xml
  feature/storedetail/src/main/res/values/strings.xml
Labels: UI 📱, FEATURE ✨, 세영 🦌

#303 [Feature/#302] 홈에서 필터링이 제대로 적용되지 않는 문제를 해결합니다.
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiCatetoryScrollableTabRow.kt
Labels: FIX 🛠️, 동민 👻
