Repository Team-Hankki/hankki-android, pull requests merged in 2025-01, with the labels that each got.

#285 [Feature/#284] change old heart
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/item/StoreItem.kt
  core/designsystem/src/main/res/drawable/ic_food.xml
  core/designsystem/src/main/res/drawable/ic_good.xml
  core/designsystem/src/main/res/drawable/ic_heart_filled.xml
  core/designsystem/src/main/res/drawable/ic_like_heart.xml
  core/designsystem/src/main/res/drawable/ic_like_heart_filled.xml
  core/designsystem/src/main/res/drawable/ic_red_like.xml
  feature/my/src/main/java/com/hankki/feature/my/component/MyStoreItem.kt
Labels: UI 📱, 혜음 🥖

#282 [Feature/#280] home category UI를 변경합니다
  core/designsystem/src/main/java/com/hankki/core/designsystem/component/chip/HankkiCategoryChip.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeState.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiCatetoryScrollableTabRow.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterBottomSheet.kt
  feature/home/src/main/java/com/hankki/feature/home/component/HankkiFilterChip.kt
  feature/home/src/main/res/drawable/ic_coin.xml
  feature/home/src/main/res/drawable/ic_empty_bowl.xml
  feature/home/src/main/res/drawable/ic_filter_btn.xml
  feature/home/src/main/res/drawable/ic_filter_btn_orange.xml
  feature/home/src/main/res/drawable/ic_sort.xml
  feature/main/src/main/java/com/hankki/feature/main/MainActivity.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
Labels: FEATURE ✨, 동민 👻

#283 [Feature/#278] share jogbo
  core/common/build.gradle.kts
  core/network/src/main/java/com/hankki/core/network/NetworkModule.kt
  core/network/src/main/java/com/hankki/core/network/Qualifier.kt
  data/login/src/main/java/com/hankki/data/login/di/ServiceModule.kt
  data/my/src/main/java/com/hankki/data/my/datasource/MyDataSource.kt
  data/my/src/main/java/com/hankki/data/my/datasourceimpl/MyDataSourceImpl.kt
  data/my/src/main/java/com/hankki/data/my/di/ServiceModule.kt
  data/my/src/main/java/com/hankki/data/my/dto/response/IsJogboOwnerResponseDto.kt
  data/my/src/main/java/com/hankki/data/my/dto/response/JogboDetailDto.kt
  data/my/src/main/java/com/hankki/data/my/repositoryimpl/MyRepositoryImpl.kt
  data/my/src/main/java/com/hankki/data/my/service/MyService.kt
  data/my/src/main/java/com/hankki/data/my/service/NoTokenMyService.kt
  data/reissuetoken/src/main/java/com/hankki/data/reissuetoken/di/ServiceModule.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/IsJogboOwnerEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/entity/response/MyJogboDetailEntity.kt
  domain/my/src/main/java/com/hankki/domain/my/repository/MyRepository.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginRoute.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginState.kt
  feature/login/src/main/java/com/hankki/feature/login/LoginViewModel.kt
  feature/login/src/main/java/com/hankki/feature/login/navigation/LoginNavigation.kt
  feature/login/src/main/res/values/strings.xml
  feature/main/build.gradle.kts
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/com/hankki/feature/main/MainActivity.kt
  feature/main/src/main/java/com/hankki/feature/main/MainNavigator.kt
  feature/main/src/main/java/com/hankki/feature/main/MainScreen.kt
  feature/my/build.gradle.kts
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbo/MyJogboViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailSideEffect.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailState.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/MyJogboDetailViewModel.kt
  feature/my/src/main/java/com/hankki/feature/my/myjogbodetail/component/JogboFolder.kt
  feature/my/src/main/java/com/hankki/feature/my/mypage/MyRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/navigation/MyNavigation.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboRoute.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboState.kt
  feature/my/src/main/java/com/hankki/feature/my/newjogbo/NewJogboViewModel.kt
  feature/my/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: FEATURE ✨, 혜음 🥖

#290 [Feature/#289] category 버저닝 및 splash UI 변경
  data/home/src/main/java/com/hankki/data/home/service/HomeService.kt
  feature/main/src/main/java/com/hankki/feature/main/splash/SplashScreen.kt
  feature/main/src/main/res/drawable/img_logo.xml
  feature/main/src/main/res/drawable/img_subtitle.xml
  feature/main/src/main/res/drawable/img_title.xml
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
Labels: FEATURE ✨, 동민 👻

#293 [Feature/#292] getUniversity함수가 실행되지 않는 버그를 수정합니다.
  feature/home/src/main/java/com/hankki/feature/home/HomeRoute.kt
  feature/home/src/main/java/com/hankki/feature/home/HomeViewModel.kt
Labels: FIX 🛠️, 동민 👻

#295 [Feature/#294] 제보화면에서 텍스트박스를 키보드가 가리는 현상을 해결합니다.
  core/common/src/main/java/com/hankki/core/common/extension/Modifier.kt
  feature/report/src/main/java/com/hankki/feature/report/main/ReportRoute.kt
Labels: FEATURE ✨, 동민 👻
